# -*- coding: utf-8 -*-
"""Tellagorla_It533_Lab02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E2IU7-nlHpSE8l8LBVsuVnkvqbCAygUJ
"""

import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
amazon = pd.read_csv("https://raw.githubusercontent.com/shstreuber/Data-Mining/master/data/amazon_toy_sample_clean.csv", encoding="ISO-8859-1") # use your own GitHub link here
amazon.dropna(inplace=True)

amazon

amazon_small = amazon.iloc[0:100,]

status_num=amazon_small.status

# Adding the new attribute to the dataframe
amazon_small['status_num'] = status_num

# Checking the contents of the new attribute
amazon_small.status_num

amazon_small.shape

amazon2=amazon
amazon2['status_num'] = amazon2.status
amazon2['status_num']= amazon2['status_num'].astype('category')
amazon2['status_num']= amazon2['status_num'].cat.codes

# Now, we check the data types
amazon2.dtypes[['status','status_num']]

status_exploration=amazon2[['status','status_num']]
status2=status_exploration.drop_duplicates()
status2.sort_values(by=['status_num'])

amazon3 = amazon
amazon3.manufacturer.unique()

amazon3.manufacturer.replace('...','Unknown', inplace=True)

# Did we indeed replace all '?'? Let's check:
amazon3[amazon3['manufacturer'] == '...']

amazon3.manufacturer.replace('Halsall','Party toys', inplace=True)
amazon3.manufacturer.replace('Neopets','Party toys', inplace=True)
amazon3.manufacturer.replace('Unique Party','Party toys', inplace=True)
amazon3.manufacturer.replace('Lord of the Rings','Regular toys', inplace=True)
amazon3.manufacturer.replace('DJI','Regular toys', inplace=True)
amazon3.manufacturer.replace('Bowen Designs','Regular toys', inplace=True)

amazon.iloc[0:5,[10,11,3,1]]

amazon2 = amazon.set_index('status')
amazon2 = amazon2.drop('new', axis=0)
amazon2.count()

bins = np.linspace(amazon.price.min(),amazon.price.max(),6)
bins

labels = ['small', 'medium', 'big']

amazon6 = amazon

buckets = [ 0, 20, 100, 500, 1000, 2500 ]
bucketlabels = ['cheap', 'a bit more', 'medium', 'pricey', 'expensive']
amazon6['buckets'] = pd.cut(amazon6['price'] , bins=buckets, labels=bucketlabels, include_lowest=True)

amazon6.groupby(['buckets']).count()

amazon.number_available_in_stock.replace('0','1', inplace=True)
amazon.number_available_in_stock.replace('0','2', inplace=True)
amazon.number_available_in_stock.replace('0','3', inplace=True)
amazon.number_available_in_stock.replace('0','4', inplace=True)
amazon.number_available_in_stock

amazon6.number_available_in_stock.replace(1,0, inplace=True)
amazon6.number_available_in_stock.replace(2,0, inplace=True)
amazon6.number_available_in_stock.replace(3,0, inplace=True)
amazon6.number_available_in_stock.replace(4,0, inplace=True)
amazon6.number_available_in_stock.count()